[[experience]]
company = "Company Name"
position = "Position Held"
timeline = "Aug. 2024 - Sep. 2025"

[[experience.project]]
type = "large"
total_rows = 6
total_cols = 6
# bg_color="#FFF"
# border_color="#FF0000"
# shadow_color="#FF0000"
[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas."
[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Project Title"
[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content = "profile.png"
[[experience.project.grid_item]]
rows = 1
cols = 1
type = "image"
content = "profile.png"
[[experience.project.grid_item]]
rows = 1
cols = 1
type = "text"
content = "Lorem ipsum"
text_color="#fff"
[[experience.project.grid_item]]
rows = 4
cols = 3
type = "model"
content = "bucket_punch.glb"
text_color="#fff"
bg_color= "#000"
[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor."
[[experience.project.grid_item]]
rows = 2
cols = 1
type = "image"
content = "profile.png"
[[experience.project.grid_item]]
rows = 2
cols = 3
type = "text"
content = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor."



[[experience]]
company = "Company Name"
position = "Position Held"
timeline = "Aug. 2024 - Sep. 2025"

[[experience.project]]
type = "small"
total_rows = 2
total_cols = 2
[[experience.project.grid_item]]
rows = 2
cols = 1
type = "text"
content = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas."
[[experience.project.grid_item]]
rows = 2
cols = 1
type = "model"
content="bucket_punch.glb"

[[experience.project]]
type = "large"
total_rows = 6
total_cols = 6
[[experience.project.grid_item]]
rows = 1
cols = 2
type = "title"
content="Project Title"
[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas."
[[experience.project.grid_item]]
rows = 2
cols = 2
type = "image"
content = "profile.png"
[[experience.project.grid_item]]
rows = 1
cols = 1
type = "image"
content = "profile.png"
[[experience.project.grid_item]]
rows = 1
cols = 1
type = "text"
content = "Lorem ipsum"
[[experience.project.grid_item]]
rows = 4
cols = 3
type = "model"
content = "bucket_punch.glb"
bg_color= "#fff"
[[experience.project.grid_item]]
rows = 2
cols = 2
type = "text"
content = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor."
[[experience.project.grid_item]]
rows = 2
cols = 1
type = "image"
content = "profile.png"
[[experience.project.grid_item]]
rows = 2
cols = 3
type = "text"
content = "Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. Ad litora torquent per conubia nostra inceptos himenaeos. Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor."
