name="Person"
description="This is my portfolio"

[[contacts]]
name = "GitHub"
link = "https://github.com/"
icon = "devicon:github"
# color = "#000000"

[[contacts]]
name = "LinkedIn"
link = "https://linkedin.com/"
icon = "devicon:linkedin"

[[contacts]]
name = "Twitter"
link = "https://twitter.com/"
icon = "devicon:twitter"
# color = "#1da1f2"

[[contacts]]
name = "Email"
link = "mailto:example@example.com"
icon = "material-symbols:alternate-email"
# color = "#000000"