name="John Doe"
description="This is my portfolio. Here is a little bit about me. Take a look at the other pages for more info."
photo="profile.png"

[[contact]]
name = "GitHub"
link = "https://github.com/"
icon = "devicon:github"
# color = "#000000"

[[contact]]
name = "LinkedIn"
link = "https://linkedin.com/"
icon = "devicon:linkedin"

[[contact]]
name = "Twitter"
link = "https://twitter.com/"
icon = "devicon:twitter"
# color = "#1da1f2"

[[contact]]
name = "Email"
link = "mailto:example@example.com"
icon = "material-symbols:alternate-email"
# color = "#000000"