[[projects]]
type = "large"
title = "This is a project title"
[projects.small_section]
type="text"
content="This is some text"
[projects.large_section]
type="model"
content = "BoxAnimated.glb"
[[projects.grid_item]]
rows = 2
cols = 2
type = "text"
content = "This is some text"
[[projects.grid_item]]
rows = 2
cols = 2
type = "model"
content = "BoxAnimated.glb"
[[projects.grid_item]]
rows = 2
cols = 2
type = "text"
content = "This is some text"
[[projects.grid_item]]
rows = 1
cols = 2
type = "image"
content = "profile.png"
[[projects.grid_item]]
rows = 1
cols = 2
type = "image"
content = "profile.png"

[[projects]]
type = "large"
title = "This is a project title"
[projects.small_section]
type="text"
content="This is some text"
[projects.large_section]
type="model"
content = "BoxAnimated.glb"
[[projects.grid_item]]
rows = 2
cols = 2
type = "text"
content = "This is some text"
[[projects.grid_item]]
rows = 2
cols = 2
type = "model"
content = "BoxAnimated.glb"
[[projects.grid_item]]
rows = 2
cols = 2
type = "text"
content = "This is some text"
[[projects.grid_item]]
rows = 1
cols = 2
type = "image"
content = "profile.png"
[[projects.grid_item]]
rows = 1
cols = 2
type = "image"
content = "profile.png"