[[section]]
name = "Programming Languages"

[[section.skill]]
name = "Python"
icon = "devicon:python"
color = "#0000FF"

[[section.skill]]
name = "Rust"
icon = "devicon:rust"
color = "#FF0000"

[[section.skill]]
name = "Java"
icon = "devicon:java"

[[section.skill]]
name = "C++"
icon = "devicon:cplusplus"
color = "#0000FF"


[[section]]
name = "Frameworks"

[[section.skill]]
name = "Svelte"
icon = "devicon:svelte"

[[section.skill]]
name = "React"
icon = "devicon:react"


[[section]]
name = "Tools"

[[section.skill]]
name = "Fusion"
icon = "devicon:fusion"