[[section]]
name = "Programming Languages"

[[section.skill]]
name = "Python"
icon = "devicon:python"
icon_size = 72
color = "#0000FF"

[[section.skill]]
name = "Rust"
icon = "devicon:rust"
color = "#FF0000"

[[section.skill]]
name = "Java"
icon = "devicon:java"

[[section.skill]]
name = "C++"
icon = "devicon:cplusplus"
color = "#0000FF"

[[section.skill]]
name = "Elixir"
icon = "devicon:elixir"
color = "#B43BFF"

[[section.skill]]
name = "Gleam"
icon = "devicon:gleam"
color = "#FFAFF3"


[[section]]
name = "Frameworks"

[[section.skill]]
name = "Svelte"
icon = "devicon:svelte"
color = "#FF7330"

[[section.skill]]
name = "React"
icon = "devicon:react"
color = "#5CDDFF"


[[section]]
name = "Tools"

[[section.skill]]
name = "Fusion"
icon = "devicon:fusion"

[[section.skill]]
name = "Blender"
icon = "devicon:blender"

[[section.skill]]
name = "Git"
icon = "devicon:git"